services:
    db:
        image: gabrielsousadeveloper/postgres-blog-database:1.0.0
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: blogdatabase
        volumes:
            - postgres_data:/var/lib/postgresql/data
        ports:
            - 5432:5432
        networks:
            - app-network

    app:
        image: gabrielsousadeveloper/fastify-blog-api:1.0.0
        ports:
            - '3000:3000'
        environment:
            FASTIFY_DATABASE_URL: 'postgresql://postgres:postgres@db:5432/blogdatabase?schema=public'
            FASTIFY_PORT: 3000
        command: sh -c 'npx prisma generate && npx prisma migrate dev --name init && npm run start'
        depends_on:
            - db
        networks:
            - app-network

volumes:
    postgres_data:

networks:
    app-network:
